In [28]:
import pandas as pd 
import numpy as np

In [29]:
df=pd.read_csv('C:\\Users\\vmuser\\Desktop\\university-course-finder\\backend\\data\\raw\\coursera_course_dataset_v3.csv')
df.head()

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,"700,909",Google Cloud Fundamentals: Core Infrastructure...,20K,Beginner,Professional Certificate,3 - 6 Months
1,1,Google Data Analytics,Google,"Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,"229,865",Prepare for a new career in the high-growth fi...,137K,Beginner,Professional Certificate,3 - 6 Months
2,3,Google Project Management:,Google,"Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,"29,702",Prepare-se para uma nova carreira no campo de ...,100K,Beginner,Professional Certificate,3 - 6 Months
3,4,IBM Data Science,IBM,"Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,"239,622",Prepare for a career in the high-growth field ...,120K,Beginner,Professional Certificate,3 - 6 Months
4,5,Google Digital Marketing & E-commerce,Google,"Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,"384,238",This course is the eighth course in the Google...,23K,Beginner,Professional Certificate,3 - 6 Months

In [30]:
df.shape

(623, 12)

In [31]:
df.columns

Index(['Unnamed: 0', 'Title', 'Organization', 'Skills', 'Ratings',
       'course_url', 'course_students_enrolled', 'course_description',
       'Review Count', 'Difficulty', 'Type', 'Duration'],
      dtype='str')

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                623 non-null    int64
 1   Title                     623 non-null    str
 2   Organization              623 non-null    str
 3   Skills                    623 non-null    str
 4   Ratings                   623 non-null    float64
 5   course_url                403 non-null    str
 6   course_students_enrolled  387 non-null    str
 7   course_description        402 non-null    str
 8   Review Count              623 non-null    str
 9   Difficulty                623 non-null    str
 10  Type                      623 non-null    str
 11  Duration                  623 non-null    str
dtypes: float64(1), int64(1), str(10)
memory usage: 58.5 KB

In [33]:
df.isnull().sum()

Unnamed: 0                    0
Title                         0
Organization                  0
Skills                        0
Ratings                       0
course_url                  220
course_students_enrolled    236
course_description          221
Review Count                  0
Difficulty                    0
Type                          0
Duration                      0
dtype: int64

In [34]:
#drop course_description which has null values since it is important for understanding about the course
df = df.dropna(subset=["course_description"])

In [35]:
df.isnull().sum()

Unnamed: 0                   0
Title                        0
Organization                 0
Skills                       0
Ratings                      0
course_url                   0
course_students_enrolled    16
course_description           0
Review Count                 0
Difficulty                   0
Type                         0
Duration                     0
dtype: int64

In [36]:
df["course_students_enrolled"] = df["course_students_enrolled"].fillna("0")

In [37]:
df["course_students_enrolled"] = (
    df["course_students_enrolled"]
    .astype(str)
    .str.replace(",", "")
    .astype(float)
)

In [38]:
df.info()

<class 'pandas.DataFrame'>
Index: 402 entries, 0 to 617
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                402 non-null    int64
 1   Title                     402 non-null    str
 2   Organization              402 non-null    str
 3   Skills                    402 non-null    str
 4   Ratings                   402 non-null    float64
 5   course_url                402 non-null    str
 6   course_students_enrolled  402 non-null    float64
 7   course_description        402 non-null    str
 8   Review Count              402 non-null    str
 9   Difficulty                402 non-null    str
 10  Type                      402 non-null    str
 11  Duration                  402 non-null    str
dtypes: float64(2), int64(1), str(9)
memory usage: 40.8 KB

In [39]:
#fix the review count column
def convert_k(x):
    if isinstance(x, str):
        x = x.replace("K", "")
        return float(x) * 1000
    return x

df["Review Count"] = df["Review Count"].apply(convert_k)

In [40]:
df.head(5)

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,700909.0,Google Cloud Fundamentals: Core Infrastructure...,20000.0,Beginner,Professional Certificate,3 - 6 Months
1,1,Google Data Analytics,Google,"Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,229865.0,Prepare for a new career in the high-growth fi...,137000.0,Beginner,Professional Certificate,3 - 6 Months
2,3,Google Project Management:,Google,"Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,29702.0,Prepare-se para uma nova carreira no campo de ...,100000.0,Beginner,Professional Certificate,3 - 6 Months
3,4,IBM Data Science,IBM,"Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,239622.0,Prepare for a career in the high-growth field ...,120000.0,Beginner,Professional Certificate,3 - 6 Months
4,5,Google Digital Marketing & E-commerce,Google,"Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,384238.0,This course is the eighth course in the Google...,23000.0,Beginner,Professional Certificate,3 - 6 Months

In [41]:
#clean skills field and make it in the form of list
df["Skills"] = df["Skills"].apply(lambda x: [s.strip() for s in x.split(",")])

In [42]:
df.head()

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,Google Cybersecurity,Google,"[Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,700909.0,Google Cloud Fundamentals: Core Infrastructure...,20000.0,Beginner,Professional Certificate,3 - 6 Months
1,1,Google Data Analytics,Google,"[Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,229865.0,Prepare for a new career in the high-growth fi...,137000.0,Beginner,Professional Certificate,3 - 6 Months
2,3,Google Project Management:,Google,"[Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,29702.0,Prepare-se para uma nova carreira no campo de ...,100000.0,Beginner,Professional Certificate,3 - 6 Months
3,4,IBM Data Science,IBM,"[Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,239622.0,Prepare for a career in the high-growth field ...,120000.0,Beginner,Professional Certificate,3 - 6 Months
4,5,Google Digital Marketing & E-commerce,Google,"[Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,384238.0,This course is the eighth course in the Google...,23000.0,Beginner,Professional Certificate,3 - 6 Months

In [43]:
#normalize text fields
df["Title"] = df["Title"].str.lower()
df["Organization"] = df["Organization"].str.lower()
df["course_description"] = df["course_description"].str.lower()

In [44]:
df.head(5)

,Unnamed: 0,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,0,google cybersecurity,google,"[Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,700909.0,google cloud fundamentals: core infrastructure...,20000.0,Beginner,Professional Certificate,3 - 6 Months
1,1,google data analytics,google,"[Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,229865.0,prepare for a new career in the high-growth fi...,137000.0,Beginner,Professional Certificate,3 - 6 Months
2,3,google project management:,google,"[Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,29702.0,prepare-se para uma nova carreira no campo de ...,100000.0,Beginner,Professional Certificate,3 - 6 Months
3,4,ibm data science,ibm,"[Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,239622.0,prepare for a career in the high-growth field ...,120000.0,Beginner,Professional Certificate,3 - 6 Months
4,5,google digital marketing & e-commerce,google,"[Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,384238.0,this course is the eighth course in the google...,23000.0,Beginner,Professional Certificate,3 - 6 Months

In [45]:
#remove the unnamed column
df = df.drop(columns=["Unnamed: 0"])

In [46]:
#find the unique values in difficulty column
df["Difficulty"].unique()

<StringArray>
['Beginner', 'Intermediate', 'Advanced', 'Mixed']
Length: 4, dtype: str

In [47]:
#standardize the difficulty column
df["Difficulty"] = (
    df["Difficulty"]
    .str.strip()
    .str.lower()
)

In [48]:
mapping = {
    "beginner": "beginner",
    "intermediate": "intermediate",
    "advanced": "advanced",
    "mixed": "all_levels"
}

df["Difficulty"] = df["Difficulty"].replace(mapping)

In [49]:
#type column unique values
df["Type"].unique()

<StringArray>
['Professional Certificate', 'Specialization', 'Course']
Length: 3, dtype: str

In [50]:
#standardize the type column
df["Type"] = df["Type"].str.strip().str.lower()

In [51]:
type_mapping = {
    "professional certificate": "professional certificate",
    "specialization": "specialization",
    "course": "course"
}

df["Type"] = df["Type"].replace(type_mapping)

In [52]:
df.head()

,Title,Organization,Skills,Ratings,course_url,course_students_enrolled,course_description,Review Count,Difficulty,Type,Duration
0,google cybersecurity,google,"[Network Security, Python Programming, Linux, ...",4.8,https://www.coursera.org/professional-certific...,700909.0,google cloud fundamentals: core infrastructure...,20000.0,beginner,professional certificate,3 - 6 Months
1,google data analytics,google,"[Data Analysis, R Programming, SQL, Business C...",4.8,https://www.coursera.org/professional-certific...,229865.0,prepare for a new career in the high-growth fi...,137000.0,beginner,professional certificate,3 - 6 Months
2,google project management:,google,"[Project Management, Strategy and Operations, ...",4.8,https://www.coursera.org/professional-certific...,29702.0,prepare-se para uma nova carreira no campo de ...,100000.0,beginner,professional certificate,3 - 6 Months
3,ibm data science,ibm,"[Python Programming, Data Science, Machine Lea...",4.6,https://www.coursera.org/professional-certific...,239622.0,prepare for a career in the high-growth field ...,120000.0,beginner,professional certificate,3 - 6 Months
4,google digital marketing & e-commerce,google,"[Digital Marketing, Marketing, Marketing Manag...",4.8,https://www.coursera.org/professional-certific...,384238.0,this course is the eighth course in the google...,23000.0,beginner,professional certificate,3 - 6 Months

In [53]:
df.to_csv("../data/processed/cleaned_courses.csv", index=False)